<?php
/**
 * @package    c1k.it
 * @author     Vino Rodrigues
 * @copyright  Tecsmith.com.au
 *   See LICENSE.TXT for copyright notice and details.
 * @license    Creative Commons Attribution-ShareAlike 3.0 Unported License
 * @author     Vino Rodrigues
 *   clickit [dot] source [at] mail [dot] vinorodrigues [dot] com
 */

if (!defined('IN_CLICKIT')) die('Restricted');

/* ------------------------------------------------------------------------- */
/* ----- DO NOT EDIT THIS FILE - OVERRIDES CAN BE SET IN ../config.php ----- */
/* ------------------------------------------------------------------------- */

/* ----- General settings (see adminset.php for help) ----- */

$settings['offline'] = FALSE;
$settings['webmaster_email'] = 'webmaster@c1k.it';
$settings['webmaster_name'] = 'c1k.it';
$settings['func_getbrowser'] = 'browser/chrisschuld.' . $phpEx;
$settings['func_lang'] = 'en.' . $phpEx;
$settings['cdn'] = 'local';
$settings['force302'] = FALSE;
$settings['cron_auto'] = TRUE;
$settings['mustlogin'] = TRUE;
$settings['allow_signup'] = TRUE;
$settings['badlogonmax'] = 3;
$settings['shortminlength'] = 4;
$settings['default_user_level'] = 1;
$settings['default_user_enabled'] = FALSE;
$settings['recaptcha_public'] = '';
$settings['recaptcha_private'] = '';
$settings['meta_description'] = "c1k.it is a URL Shortening service, or URL shortener, hosted by Tecsmith.com.au for it's internet marketing clients";
$settings['meta_keywords'] = "URL shortening,URL shortener,Clean URL,Link rot,Semantic URL,URL redirection,Vanity domain,Vanity URL,internet marketing,online marketing,marketing";
$settings['facebook_id'] = '';
$settings['twitter_key'] = '';
$settings['twitter_follow_list'] = 'tcsmth';
$settings['piwik_site'] = '';
$settings['piwik_site_secure'] = '';
$settings['piwik_id'] = '';
$settings['ga_profile'] = '';

/* ----- Database Settings (overrides set by install.php in ../config.php) ----- */

$settings['dbms']     = 'mysqli';
$settings['dbhost']   = 'localhost';
$settings['dbuser']   = 'root';
$settings['dbpasswd'] = '';
$settings['dbname']   = 'clickit';
$settings['dbport']   = '';
$settings['dbprefix'] = 'c1k_';

?>
